package ru.privatenull.pnauth.extension

enum class AuthOperation {
    ADMISSION, JOIN, REGISTER, LOGIN, LOGOUT, CHANGE_PASSWORD, UNREGISTER,
    TOTP_SETUP, TOTP_VERIFY, TOTP_DISABLE, PREMIUM_CHANGE, SERVER_ACCESS, COMMAND, CHAT,
    ADMIN_FORCE_LOGIN, ADMIN_FORCE_REGISTER, ADMIN_UNREGISTER, ADMIN_CHANGE_PASSWORD
}
