plugins {
    id 'com.gradleup.shadow'
    id 'application'
}

dependencies {
    implementation project(':shared')
    implementation 'net.elytrium:serializer:1.1.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
}

application {
    mainClass = 'ru.privatenull.pnauth.hub.PnAuthHubKt'
}

tasks.named('shadowJar') {
    archiveFileName = "pnAuth-hub-${project.version}.jar"
    archiveClassifier = ''
    mergeServiceFiles()
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    filesMatching('META-INF/services/**') { duplicatesStrategy = DuplicatesStrategy.INCLUDE }
    filesMatching('META-INF/*.kotlin_module') { duplicatesStrategy = DuplicatesStrategy.INCLUDE }
    manifest { attributes('Main-Class': application.mainClass.get()) }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
}

tasks.named('build') { dependsOn tasks.named('shadowJar') }
